### PR TITLE
Ft checkbox

### PR DESCRIPTION
**Pull request by BrendaNamutebi**
PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

#### Summary of Changes (What does this PR do?)
- I  created a re-usable form component for a checkbox, that i used in other components 

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Jira Ticket(s) Number
- [ticket-id](SA-22)

## Screenshots/Videos
checkbox3

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Review by khalifan-kfan — APPROVED** [review]

**Review by FaithDaka — CHANGES_REQUESTED** [review]
Nice work @BrendaNamutebi 
1. Would love to see the component implemented on page 3 of the seizure assessment
Screenshot (108)

2. Does the component allow for multiple choice selection of input?
3. On form submission, are these values correctly captured by the seizure redux slice?

Also, did you find any issues implementing the small _checked tick_ as shown in the designs? The one you've implemented is quite curved
Screenshot (109)

**Comment by FaithDaka** [comment]
Please add the JIRA ticket number to your PR description, and make sure the latest changes have been merged to your branch (so as to check it)

**Comment by BrendaNamutebi** [comment]
1.okay i'm working on it now
2.yes it allows multiple choice selection
3.not yet sure
loginfail

**Comment by BrendaNamutebi** [comment]
hello, faith how would you like the checkboxes to appear(in two columns or one)but i had re-used the checkbox form component in seizure tracking as shown below
seizure

**Comment by BrendaNamutebi** [comment]
kindly review this!!!

seizure tracker

**Comment by FaithDaka** [comment]
@BrendaNamutebi I can see that the rest of the components on this form have been pushed to beyond the **Finish** button. A user won't be able to access the slider for the _Did it upset you?_ question.
Therefore the checkbox component for this page should be adjusted to allow all the questions to fit in the space above the button i.e it should be responsive. And from what I can see the checkboxes are still quite large (large height) and have a large padding.

**Comment by BrendaNamutebi** [comment]
@FaithDaka,Is it okay now?
seizure2

**Review by FaithDaka — APPROVED** [review]
LGTM!
Thanks for the designs @BrendaNamutebi

**Comment by FaithDaka** [comment]
@BrendaNamutebi please resolve the merge conflicts and let's have this merged.

**Pull request merged**
