### PR TITLE
enable user to delete medicine

### PR DESCRIPTION
**Pull request by khalifan-kfan**
PR Checklist (Make sure these options are checked before raising the PR)

- [ ] - Latest `master` branch merged
- [ ] - Descriptive PR title (can be used in release notes)

#### Summary of Changes (What does this PR do?)
-  Enable User delete a medicine from their profile

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Jira Ticket(s) Number
- SA-100

## Screenshots/Videos
image

### CODE REVIEW

**Comment by FaithDaka** [comment]
Thanks for this @khalifan-kfan. The deletion works well 

A few points to change:
1. Can the delete icon match the design style of icons in the app? Which is filled icons with the purple color. You can ask Denis for a custom if you need to.
2. Since this is a deletion feature, it will be nice to have a prompt before actual deletion. A pop up that asks the user "**Are you sure you want to delete {_medicine_name_}?**" Because deleting is a serious action, you want to make sure that if someone accidently clicks the delete button, they don't lose their medicine.

Let me know if that makes sense

**Comment by khalifan-kfan** [comment]
Makes sense Thanks @FaithDaka

**Comment by khalifan-kfan** [comment]
Handled @FaithDaka 
image

**Comment by FaithDaka** [comment]
Great work @khalifan-kfan

**Pull request merged**
