### PR TITLE
ui feedback

### PR DESCRIPTION
**Pull request by khalifan-kfan**
PR Checklist (Make sure these options are checked before raising the PR)

- [ ] - Latest `master` branch merged
- [ ] - Descriptive PR title (can be used in release notes)

#### Summary of Changes (What does this PR do?)
-  Work on UI feedback and bugs
This involves 
Enable deletion of grateful (items)
Fix meditation image
Fix Medication side effect issue
fix the positioning of save gratefuls
work on medicine reminder time seletor alignment

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Jira Ticket(s) Number
- SA-120

## Screenshots/Videos

image

### CODE REVIEW

**Comment by FaithDaka** [comment]
@khalifan-kfan I see that the changes in this branch have changed the CSS I had implemented for the _Journaling_ component which might mean:
1. You might have added clashing CSS classes, or
2. This branch is not up to date with the _main_ branch

Styling in main branch:
image

Styling in this branch:
image

**Comment by FaithDaka** [comment]
The other thing is that the design style is still not matching that of the app. 
These components seem out of place from a UI stand point. They don't maintain that consistency

**Comment by khalifan-kfan** [comment]
Thanks @FaithDaka for this catch
fixed it
image

**Comment by khalifan-kfan** [comment]
You would need to elaborate more on the second comment as I was implementing something similar to what Grace had mentioned
Changed the icon colors though
image

**Comment by FaithDaka** [comment]
@khalifan-kfan The delete of a grateful is not working
image

The other thing is that when creating a delete in the frontend, it is always good to verify that decision with the user i.e
1. User clicks the delete icon
2. A modal pops up to ask them if they are sure they want to delete the item (this mitigates accidental clicks)
3. If they choose to cancel, the item is **not** deleted
4. If they choose to continue, the item is deleted

**Comment by khalifan-kfan** [comment]
Hello @FaithDaka  please review this once more, the grateful Delete action has been fixed.
This PR also contains some of the currently requested for feedback

**Pull request merged**
